---
- name: Ansible-HomeLab
  hosts: all
  roles:
    - role: general
      tags:
        - general

    # - role: vladgh.samba.server
    #   tags:
    #     - samba

    - role: geerlingguy.docker
      tags:
        - docker
      become: true

    - role: kvm
      tags:
        - kvm

# - name: Install docker
#   hosts: docker
#   roles:
#     - role: geerlingguy.docker
#       tags: ['docker']
