---
roles:
  - name: geerlingguy.docker

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general
  - name: prometheus.prometheus
  - name: grafana.grafana
# ansible-galaxy collection install git+https://github.com/k3s-io/k3s-ansible.git
  - name: git+https://github.com/k3s-io/k3s-ansible.git
