---
all:
  hosts:
    y9000p:
      ansible_host: 10.66.66.3
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3.11
  children:
    docker:
      hosts:
        y9000p:
