---
all:
  hosts:
    y9000p:
      ansible_host: 192.168.50.93
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3
    b360m:
      ansible_host: 192.168.50.94
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3
  children:
    # docker:
    #   hosts:
    #     y9000p:
    #     b360m:
    k3s_cluster:
      children:
        server:
          hosts:
            y9000p:
        agent:
          hosts:
            b360m:
