# roles/immich/tasks/main.yml
---
- name: Start immich
  block:
    - name: Ensure all immich directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
        recurse: false # 统一应用您期望的非递归策略
      loop:
        - "{{ immich_dir }}"
        - "{{ immich_dir }}/cache"
        - "{{ immich_dir }}/database"
        - "{{ immich_data_dir }}"
      become: true

    - name: Immich redis Docker Container
      community.docker.docker_container:
        name: immich_redis
        image: docker.io/valkey/valkey:8-bookworm@sha256:facc1d2c3462975c34e10fccb167bfa92b0e0dbd992fc282c29a61c3243afb11
        networks:
          - name: "{{ docker_shared_network_name }}"
        env:
          TZ: "{{ timezone }}"
        healthcheck:
          test: ["CMD", "redis-cli", "ping", "||", "exit", "1"]
        restart_policy: always

    - name: Immich database Docker Container
      community.docker.docker_container:
        name: immich_postgres
        image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:32324a2f41df5de9efe1af166b7008c3f55646f8d0e00d9550c16c9822366b4a
        networks:
          - name: "{{ docker_shared_network_name }}"
        env:
          TZ: "{{ timezone }}"
          POSTGRES_PASSWORD: "{{ immich_database_password }}"
          POSTGRES_USER: "{{ immich_database_user_name }}"
          POSTGRES_DB: "{{ immich_database_name }}"
          POSTGRES_INITDB_ARGS: "--data-checksums"
        volumes:
          - "{{ immich_dir }}/database:/var/lib/postgresql/data"
        shm_size: "128M"
        restart_policy: always

    - name: Start immich Container
      community.docker.docker_container:
        name: immich_server
        image: "ghcr.io/immich-app/immich-server:{{ immich_image_version }}"
        networks:
          - name: "{{ docker_shared_network_name }}"
        ports:
          - 22833:2283
        volumes:
          - "{{ immich_data_dir }}:/data"
        env:
          TZ: "{{ timezone }}"
          DB_HOSTNAME: "immich_postgres"
          DB_USERNAME: "{{ immich_database_user_name }}"
          DB_PASSWORD: "{{ immich_database_password }}"
          DB_DATABASE_NAME: "{{ immich_database_name }}"
          REDIS_HOSTNAME: "immich_redis"
        device_requests:
          - driver: nvidia
            count: -1 # this means we want all
            capabilities:
              - - gpu
                - compute
                - video
        restart_policy: always

    - name: Start immich machine learning Container
      community.docker.docker_container:
        name: immich_machine_learning
        image: "ghcr.io/immich-app/immich-machine-learning:{{ immich_image_version }}"
        networks:
          - name: "{{ docker_shared_network_name }}"
        volumes:
          - "{{ immich_dir }}/cache:/cache"
        env:
          TZ: "{{ timezone }}"
        device_requests:
          - driver: nvidia
            count: -1 # this means we want all
            capabilities:
              - - gpu
        restart_policy: always
  when: immich_enabled is true
