---
# roles/kvm/vars/main.yml

kvm_packages:
  - qemu-kvm
  - libvirt-clients
  - libvirt-daemon-system
  - bridge-utils
  - virtinst
  - libvirt-daemon
  # virt-manager is optional for GUI management
  # - virt-manager
  - resolvconf # Needed for DNS management via interfaces file
